// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQkwAQ1z5mxQCxqNeItMa1H7bFzN8dfJU',
    appId: '1:477098134436:web:d3d976e32454169a91cf31',
    messagingSenderId: '477098134436',
    projectId: 'flutter-icard',
    authDomain: 'flutter-icard.firebaseapp.com',
    storageBucket: 'flutter-icard.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUhNtT_6EpsfdpIZp3aaW7r7HpS_3bI3s',
    appId: '1:477098134436:android:25143240e7c5eaa691cf31',
    messagingSenderId: '477098134436',
    projectId: 'flutter-icard',
    storageBucket: 'flutter-icard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBRYFOwe6URb3owFN21E6fK66NhscvAT8',
    appId: '1:477098134436:ios:284fe2f1c3c61b1e91cf31',
    messagingSenderId: '477098134436',
    projectId: 'flutter-icard',
    storageBucket: 'flutter-icard.appspot.com',
    iosClientId: '477098134436-r1vvjjh9edgg475penmb2fqv0g2rtdav.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2312LoginFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBRYFOwe6URb3owFN21E6fK66NhscvAT8',
    appId: '1:477098134436:ios:284fe2f1c3c61b1e91cf31',
    messagingSenderId: '477098134436',
    projectId: 'flutter-icard',
    storageBucket: 'flutter-icard.appspot.com',
    iosClientId: '477098134436-r1vvjjh9edgg475penmb2fqv0g2rtdav.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2312LoginFire',
  );
}
